import os
import json
import glob

def main():
    json_files = glob.glob("crashes/crash_report_*.json")
    if not json_files:
        print("No Mutagen crash reports found.")
        return

    total_crashes = 0
    vuln_rows = []
    patch_sections = []

    for report_path in json_files:
        try:
            with open(report_path, "r", encoding="utf-8") as f:
                report = json.load(f)
        except Exception as e:
            print(f"Error reading {report_path}: {e}")
            continue

        target = report.get("target", "unknown")
        crashes = report.get("crashes", [])
        total_crashes += len(crashes)

        for c in crashes:
            severity = c.get("severity", "unknown").upper()
            # Style severity bold/color using markdown if needed, bold is standard
            severity_str = f"**{severity}**"
            if severity == "CRITICAL":
                severity_str = f"🔴 **CRITICAL**"
            elif severity == "HIGH":
                severity_str = f"🟠 **HIGH**"
            elif severity == "MEDIUM":
                severity_str = f"🟡 **MEDIUM**"
            elif severity == "LOW":
                severity_str = f"🟢 **LOW**"

            vuln_type = c.get("vuln_type", "unknown")
            cwe = c.get("cwe", "N/A")
            crash_type = c.get("crash_type", "N/A")
            
            vuln_rows.append(
                f"| `{target}` | {severity_str} | {vuln_type} | {cwe} | `{crash_type}` |"
            )

        # Check for patch file across all supported languages
        supported_exts = ["c", "cpp", "rs", "go", "java", "cs"]
        found_patch = None
        found_ext = None
        for ext in supported_exts:
            path = f"patches/{target}_FIXED.{ext}"
            if os.path.exists(path):
                found_patch = path
                found_ext = ext
                break
                
        if found_patch:
            try:
                with open(found_patch, "r", encoding="utf-8") as f:
                    patch_code = f.read()
                
                lang_mapping = {
                    "c": "c",
                    "cpp": "cpp",
                    "rs": "rust",
                    "go": "go",
                    "java": "java",
                    "cs": "csharp"
                }
                md_lang = lang_mapping.get(found_ext, "text")
                
                patch_sections.append(
                    f"#### Target: `{target}.{found_ext}`\n"
                    f"<details>\n"
                    f"<summary><b>🩹 View Auto-Generated Secure Patch</b></summary>\n\n"
                    f"```{md_lang}\n"
                    f"{patch_code}\n"
                    f"```\n\n"
                    f"</details>"
                )
            except Exception as e:
                print(f"Error reading patch {found_patch}: {e}")

    if total_crashes == 0:
        print("No crashes found in reports.")
        return

    # Construct comment.md
    markdown_content = f"""## 🧬 Mutagen Security Analysis Report

Mutagen has completed automated security fuzzing on the modified targets in this Pull Request and identified **{total_crashes}** unique vulnerability crash(es).

### 🚨 Vulnerability Summary

| Target | Severity | Vulnerability Type | CWE | Crash Signal |
|--------|----------|-------------------|-----|--------------|
"""
    markdown_content += "\n".join(vuln_rows) + "\n\n"
    
    if patch_sections:
        markdown_content += "### 🩹 Auto-Generated C Patches\n\n"
        markdown_content += "The following secure patches were generated and verified by Mutagen's self-healing loop:\n\n"
        markdown_content += "\n\n".join(patch_sections) + "\n\n"
    
    markdown_content += """---
*Report generated by **Mutagen v2.0** - Shift-Left AI Fuzzing & Auto-Patching.*
"""

    with open("comment.md", "w", encoding="utf-8") as f:
        f.write(markdown_content)
    
    print("Successfully generated comment.md")

if __name__ == "__main__":
    main()
