import os
import subprocess
import tempfile

from rich.console import Console

console = Console(force_terminal=True, force_jupyter=False)

def generate_decompile_headless_script(output_py_path: str, output_c_path: str):
    """Generates a Ghidra Jython script to dump decompiled pseudo-C functions."""
    script_content = f'''# Headless Ghidra Decompiler Script
import os
from ghidra.app.decompiler import DecompInterface
from ghidra.util.task import ConsoleTaskMonitor

out_path = r"{output_c_path}"
decomp = DecompInterface()
decomp.openProgram(currentProgram)

monitor = ConsoleTaskMonitor()
functionManager = currentProgram.getFunctionManager()
functions = functionManager.getFunctions(True)

lines = []
lines.append("// Decompiled pseudo-C generated by Ghidra Headless Analyzer\\n")

for func in functions:
    res = decomp.decompileFunction(func, 30, monitor)
    if res.decompiledFunction:
        lines.append(res.decompiledFunction.getC())
        lines.append("\\n\\n")

with open(out_path, "w") as f:
    f.write("".join(lines))
'''
    with open(output_py_path, "w", encoding="utf-8") as f:
        f.write(script_content)

def decompile_with_ghidra_headless(binary_path: str, ghidra_home: str | None = None) -> str | None:
    """Executes Ghidra analyzeHeadless to decompile a binary target into pseudo-C source code."""
    if not ghidra_home:
        ghidra_home = os.environ.get("GHIDRA_HOME", "")

    analyze_headless = None
    if ghidra_home and os.path.exists(ghidra_home):
        candidate = os.path.join(ghidra_home, "support", "analyzeHeadless.bat" if os.name == 'nt' else "analyzeHeadless")
        if os.path.exists(candidate):
            analyze_headless = candidate

    if not analyze_headless:
        # Search PATH
        analyze_headless = shutil_which("analyzeHeadless.bat" if os.name == 'nt' else "analyzeHeadless")

    if not analyze_headless:
        return None

    console.print(f"[cyan]  [+] Ghidra Headless Analyzer detected! Decompiling binary '{os.path.basename(binary_path)}'...[/cyan]")

    with tempfile.TemporaryDirectory() as tmpdir:
        script_py = os.path.join(tmpdir, "DecompileHeadless.py")
        output_c = os.path.join(tmpdir, "decompiled.c")
        project_dir = os.path.join(tmpdir, "ghidra_proj")
        os.makedirs(project_dir, exist_ok=True)

        generate_decompile_headless_script(script_py, output_c)

        cmd = [
            analyze_headless,
            project_dir,
            "TempProj",
            "-import", binary_path,
            "-postScript", script_py,
            "-deleteProject"
        ]

        try:
            subprocess.run(cmd, capture_output=True, text=True, timeout=120)
            if os.path.exists(output_c):
                with open(output_c, encoding="utf-8", errors="ignore") as f:
                    pseudo_c = f.read()
                if pseudo_c.strip():
                    return pseudo_c
        except Exception as e:
            console.print(f"[yellow]  [!] Ghidra Headless Decompilation error: {e}[/yellow]")

    return None

def shutil_which(cmd: str) -> str | None:
    import shutil
    return shutil.which(cmd)
