from mutagen.agents.base import BaseAgent
from mutagen.constants import DEFAULT_MODEL_GEMINI, DEFAULT_PROVIDER
from mutagen.engines import get_engine
from mutagen.state import ProgramContext


class PatchEngineerAgent(BaseAgent):
    def __init__(self, model_provider: str = DEFAULT_PROVIDER, model_name: str = DEFAULT_MODEL_GEMINI, api_key: str = None):
        super().__init__("Patch Engineer Agent", model_provider, model_name, api_key)
        self.engine = get_engine(model_provider, self.api_key, model_name)

    async def process(self, context: ProgramContext) -> ProgramContext:
        self.engine.language = context.language
        context.logs.append("[PatchEngineerAgent] Generating secure patch code...")

        # Get the first crash payload that triggered
        crash = None
        for p in context.active_payloads:
            if p.crash_type is not None:
                crash = p
                break

        if not crash:
            context.logs.append("[PatchEngineerAgent] No crashes detected to patch.")
            return context

        # Format target reasoning using notepad history if available
        reasoning = f"Triggered by crash payload args: {crash.args}"
        if context.notepad:
            reasoning += "\nPrevious Swarm Notepad Notes:\n" + "\n".join(f"- {note}" for note in context.notepad)

        # Resolve CWE: use the first specific (non-default) CWE from triage findings, fall back to CWE-120
        matched_cwe = "CWE-120"
        for v in context.vulnerabilities:
            if v.cwe and v.cwe != "CWE-120":
                matched_cwe = v.cwe
                break


        crash_data = {
            "vuln_type": crash.crash_type,
            "args": crash.args,
            "input_data": crash.input_data,
            "raw_bytes_hex": crash.raw_bytes_hex,
            "cwe": matched_cwe,
            "severity": "critical",
            "reason": reasoning
        }

        # Check if we have a previous bad patch to refine
        bad_patch = context.get_primary_patch()

        from rich.console import Console
        console = Console(force_terminal=True, force_jupyter=False)

        if bad_patch and context.verification_status != "VERIFIED_SECURE":
            context.logs.append("[PatchEngineerAgent] Refining previous failed patch...")
            console.print(f"[dim]  🤖 [PatchEngineerAgent] Refining patch using AI engine '{self.model_provider}' (Model: {self.model_name or DEFAULT_MODEL_GEMINI})...[/dim]")
            from mutagen.engines.output_parser import strip_code_fences
            clean_bad_patch = strip_code_fences(bad_patch)
            # Retrieve last log or compilation error
            error_message = context.logs[-1] if context.logs else "Unknown verification error"
            if context.notepad:
                error_message += "\n\nShared Swarm Notepad history:\n" + "\n".join(f"- {note}" for note in context.notepad)

            patched_code = self.engine.refine_patch(
                source_code=context.source_code,
                bad_patch=clean_bad_patch,
                error_message=error_message,
                crash_data=crash_data,
                debug=True
            )
        else:
            context.logs.append("[PatchEngineerAgent] Generating fresh initial patch...")
            console.print(f"[dim]  🤖 [PatchEngineerAgent] Generating fresh patch using AI engine '{self.model_provider}' (Model: {self.model_name or DEFAULT_MODEL_GEMINI})...[/dim]")
            patched_code = self.engine.generate_patch(
                source_code=context.source_code,
                crash_data=crash_data,
                debug=True
            )

        if patched_code:
            context.set_primary_patch(patched_code)
            context.logs.append("[PatchEngineerAgent] Proposed patch saved.")
            context.notepad.append(f"PatchEngineerAgent: Proposed secure patch implementation (Revision {len(context.notepad) + 1})")
            console.print("[dim]  ✓ Secure patch candidate generated by AI engine.[/dim]")
        else:
            context.logs.append("[PatchEngineerAgent] Failed to generate patch.")
            console.print("[bold yellow]  ⚠️ AI engine was unable to produce a patch candidate.[/bold yellow]")

        return context
